Ejemplo_1/Models/Mascota.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejemplo_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mascota
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Raza { get; set; }
        public Nullable<int> Edad { get; set; }
        public string NombreDueno { get; set; }
    }
}

Ejemplo_1/Models/MascotasContext.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejemplo_1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MascotasConnection : DbContext
    {
        public MascotasConnection()
            : base("name=MascotasConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Mascota> Mascota { get; set; }
    }
}

Ejemplo_1/Models/MascotasContext.Designer.cs
// La generación de código T4 está habilitada para el modelo 'C:\Users\claud\OneDrive\Escritorio\ASPNetCore101\CodeSkills_Mascotas\Ejemplo_1\Models\MascotasContext.edmx'. 
// Para habilitar la generación de código heredada, cambie el valor de la propiedad del diseñador 'Estrategia de generación de código'
// por 'ObjectContext heredado'. Esta propiedad está disponible en la ventana Propiedades cuando se abre
// el modelo en el diseñador.

// Si no se ha generado ninguna clase de contexto y de entidad, puede que haya creado un modelo vacío pero
// no haya elegido todavía la versión de Entity Framework que se va a usar. Para generar una clase de contexto y clases de entidad
// para el modelo, abra el modelo en el diseñador, haga clic con el botón secundario en la superficie del diseñador y
// seleccione 'Actualizar modelo desde base de datos...', 'Generar base de datos desde modelo...' o 'Agregar elemento de generación
// de código...'.

Ejemplo_1/Models/MascotasContext.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

Ejemplo_1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ejemplo_1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        

       
    }
}

Ejemplo_1/Controllers/MascotaController.cs
using Ejemplo_1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace Ejemplo_1.Controllers
{
    public class MascotaController : Controller
    {
        private MascotasConnection BD;
        public MascotaController()
        {
            BD = new MascotasConnection();
        }
        

        // GET: Mascota
        public ActionResult Index()
        {
            var listado = BD.Mascota.ToList();
            return View(listado);
        }
        //Este metodo me envia a la vista nuevo(formulario)
        public ActionResult Nuevo()
        {            
            return View();
        }

        //Este metodo se usa cuando se envia una nueva mascota(POST)
        [HttpPost]
        public ActionResult Nuevo(Mascota mascota)
        {
            BD.Mascota.Add(mascota);
            BD.SaveChanges();
            //Redireccionamos a la vista index para chequear q se agrego
            return RedirectToAction("Index");
        }

        //1ºmetodo Actualizar, pinta la pagina y recibe el objeto
        [HttpGet]
        public ActionResult Actualizar(int id)
        {            
            var mascota = BD.Mascota.FirstOrDefault(x => x.Id == id);
            return View(mascota);
        }
        //2ºmetodo Actualizar, postea los cambios del objeto modificado
        [HttpPost]
        public ActionResult Actualizar(Mascota mascota)
        {            
            var mascotaActual = BD.Mascota.FirstOrDefault(x => x.Id == mascota.Id);
            mascotaActual.Edad = mascota.Edad;
            mascotaActual.Nombre = mascota.Nombre;
            mascotaActual.Raza = mascota.Raza;
            mascotaActual.NombreDueno = mascota.NombreDueno;
            BD.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            var mascotaAEliminar = BD.Mascota.FirstOrDefault(x=>x.Id==id);
            BD.Mascota.Remove(mascotaAEliminar);
            BD.SaveChanges();
            return RedirectToAction("Index");
        }
        private List<Mascota> obtenerMascotas()
        {
            var listaMascotas = new List<Mascota>();
            listaMascotas.Add(new Mascota { Id = 1, Nombre="Felipe",Raza="Perro",Edad=3,NombreDueno="Leo"});
            listaMascotas.Add(new Mascota { Id = 2, Nombre = "Paco", Raza = "Loro", Edad = 4, NombreDueno = "Cristian" });
            listaMascotas.Add(new Mascota { Id = 3, Nombre = "Michi", Raza = "Gato", Edad = 2, NombreDueno = "Claudio" });
            listaMascotas.Add(new Mascota { Id = 4, Nombre="Vitto", Raza="Perro", Edad=4, NombreDueno="Mauro"});
            listaMascotas.Add(new Mascota { Id = 5, Nombre="Raffael", Raza="Tortuga", Edad=7, NombreDueno="Guille" });
            return listaMascotas;
        }
    }
}

Ejemplo_1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

Ejemplo_1/Views/Mascota/Actualizar.cshtml
@model Ejemplo_1.Models.Mascota
@{
    ViewBag.Title = "Actualizar";
}

<h2>Actualizar Mascota</h2>



<form action="@Url.Action("Actualizar","Mascota")" method="post">
    <div class="row">
        <div class="col-6">
            <div class="mb-3 form-group">
                <label>Id</label>
                @Html.TextBoxFor(x => x.Id, new { @class = "form-control", @required = "required" })
            </div>
            <div class="mb-2 form-group">
                <label>Nombre</label>
                @Html.TextBoxFor(x => x.Nombre, new { @class = "form-control", @required = "required" })
            </div>
            <div class="mb-3 form-group">
                <label>Raza</label>
                @Html.TextBoxFor(x => x.Raza, new { @class = "form-control", @required = "required" })
            </div>
            <div class="mb-3 form-group">
                <label>Edad</label>
                @Html.TextBoxFor(x => x.Edad, new { @class = "form-control", @required = "required" })
            </div>
            <div class="mb-3 form-group">
                <label>Dueño</label>
                @Html.TextBoxFor(x => x.NombreDueno, new { @class = "form-control", @required = "required" })
            </div>
            <div>
                <input type="submit" class="btn btn-primary" value="Guardar" />
                <a href="@Url.Action("Index","Mascota")" class="btn btn-danger">Regresar</a>
            </div>
        </div>
    </div>
</form>

Ejemplo_1/Views/Mascota/Index.cshtml
@model List<Ejemplo_1.Models.Mascota>
@{
    ViewBag.Title = "Index";
}

<div class="d-flex justify-content-between">
    <h2>Listado de Mascotas</h2>
    <a href="@Url.Action("Nuevo","Mascota")" class="btn btn-success">Nuevo</a>
</div>

<hr />
<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Nombre</th>
            <th scope="col">Raza</th>
            <th scope="col">Edad</th>
            <th scope="col">Nombre Dueño</th>
            <th scope="col">Accion</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var mascota in Model)
        {
            <tr>
                <th scope="row">@mascota.Id</th>
                <td>@mascota.Nombre</td>
                <td>@mascota.Raza</td>
                <td>@mascota.Edad</td>
                <td>@mascota.NombreDueno</td>
                <td>
                    <a href="@Url.Action("Actualizar","Mascota", new {id=@mascota.Id})" class="btn btn-primary">Actualizar</a>
                    <a href="@Url.Action("Eliminar", "Mascota", new { id = @mascota.Id })" class="btn btn-danger">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Ejemplo_1/Views/Mascota/Nuevo.cshtml
@model Ejemplo_1.Models.Mascota
@{
    ViewBag.Title = "Nuevo";
}

<h2>Nueva Mascota</h2>

@* Esta accion va al Segundo metodo httpPost Nuevo q recibe una mascota, osea cuando se clikea en btn guardar *@
<form action="@Url.Action("Nuevo","Mascota")" method="post">
    <div class="row">
        <div class="col-6">
            <div class="mb-3 form-group">
                <label>Id</label>
                @Html.TextBoxFor(x => x.Id, new { @class = "form-control", @required = "required" })
            </div>
            <div class="mb-2 form-group">
                <label>Nombre</label>
                @Html.TextBoxFor(x => x.Nombre, new { @class = "form-control", @required = "required" })
            </div>
            <div class="mb-3 form-group">
                <label>Raza</label>
                @Html.TextBoxFor(x => x.Raza, new { @class = "form-control", @required = "required" })
            </div>
            <div class="mb-3 form-group">
                <label>Edad</label>
                @Html.TextBoxFor(x => x.Edad, new { @class = "form-control", @required = "required" })
            </div>
            <div class="mb-3 form-group">
                <label>Dueño</label>
                @Html.TextBoxFor(x => x.NombreDueno, new { @class = "form-control", @required = "required" })
            </div>
            <div>
                <input type="submit" class="btn btn-primary" value="Guardar" />
                <a href="@Url.Action("Index","Mascota")" class="btn btn-danger">Regresar</a>
            </div>
        </div>
    </div>
</form>

Ejemplo_1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MascotasApp</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("MascotasApp", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Mascotas", "Index", "Mascota", new { area = "" }, new { @class = "nav-link" })</li>                    
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>